# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def all_pods
    pod 'RxSwift', '~> 4.5'
    pod 'RxCocoa', '~> 4.5'
    pod 'RxBlocking', '~> 4.5'
    pod 'Nuke', '~> 7.0'

end

target 'ecomerce-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ecomerce-iOS

  all_pods

  target 'ecomerce-iOSTests' do
    inherit! :search_paths
    # Pods for testing

     all_pods
  end

  target 'ecomerce-iOSUITests' do
    # Pods for testing
  end

end
